services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DEBIAN_FRONTEND: noninteractive
    volumes:
      - type: bind
        source: ./output
        target: /output